# Generated by Django 3.0 on 2020-05-30 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_Url', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Published_Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type1', models.BooleanField(default=False)),
                ('type2', models.BooleanField(default=False)),
                ('type3', models.BooleanField(default=False)),
                ('related', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='WN_Content.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Feedback', models.TextField()),
                ('Date', models.DateTimeField()),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WN_Content.Post')),
            ],
        ),
    ]
