# Generated by Django 3.0 on 2020-06-12 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WN_Content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='type1',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='type2',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='type3',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WN_Content.Post'),
        ),
    ]
