# Generated by Django 3.0 on 2020-06-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WN_Content', '0003_user_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
