# Generated by Django 3.0 on 2020-07-10 21:07

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WN_Content', '0006_auto_20200710_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Video_Url',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
